[package]
name = "qbels"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "0.14.0"
tokio = { version = "1.46.1", features = ["full"] }
tower-lsp-server = "0.22.0"
tree-sitter = "0.25.8"
tree-sitter-qbe = { git = "https://github.com/mkanilsson/tree-sitter-qbe.git", version = "0.1.0" }
